name: build and release

on:
  workflow_dispatch:
    inputs:      
      tag:
        description: 'Release Tag'
        required: true        

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        device: [d2s]
        su: [non-ksu, ksu]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update -y  
          sudo apt install libncurses5-dev python2 libtinfo5 -y    
          git clone --depth=1 https://github.com/ravindu644/proton-12.git -b main --single-branch proton
          export PATH=$PWD/proton/bin:$PATH  
          
      - name: Set environment variable
        run: |
          echo "LPOS_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          
      - name: Building LPoS
        run: |
          if [ "${{ matrix.su }}" == "non-ksu" ]; then
            bash build.sh ${{ matrix.device }} non-ksu
          else
            bash build.sh ${{ matrix.device }} ksu
          fi

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: "LPoS-${{ env.LPOS_KERNEL_VERSION }}-${{ matrix.device }}-${{ matrix.su }}-universal"
          path: |
            build/*.zip
